# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  # The command to build your app
  cmd = "go build -o ./tmp/api ."
  # The binary to run (arguments moved to args_bin so the subcommand executes)
  bin = "./tmp/api"
  # Arguments passed to the binary so it doesn't just print help and exit
  args_bin = ["apiserver"]
  # Watch these file extensions
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Ignore these directories
  exclude_dir = ["tmp", "vendor", "testdata", "bin", "docs"]
  # Log file for build errors
  log = "air_errors.log"
  # Delay in milliseconds before restarting
  delay = 1000
  # Stop on first error
  stop_on_error = true

[log]
  # Show time in logs
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Clean up tmp dir on exit
  clean_on_exit = true
