# .air.schedule.toml
root = "."
tmp_dir = "tmp-schedule"

[build]
  # Build schedule binary
  cmd = "go build -o ./tmp/schedule ."
  # Run schedule subcommand
  bin = "./tmp/schedule"
  # Ensure the subcommand is 'schedule'
  args_bin = ["schedule"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "testdata", "bin", "docs"]
  log = "air_schedule_errors.log"
  delay = 1000
  stop_on_error = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
