version: "2"
run:
  modules-download-mode: mod
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    lll:
      line-length: 150
      tab-width: 1

    revive:
      # rules:
      #   # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#var-naming
      #   - name: var-naming
      #     severity: warning
      #     disabled: true
      #     exclude: [""]
      #     arguments:
      #       - [ "ID" ] # AllowList
      #       - [ "VM" ] # DenyList
      #       - - skip-initialism-name-checks: true
      #           upper-case-const: true
      #           skip-package-name-checks: true
      #           extra-bad-package-names:
      #             - helpers
      #             - models
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
