services:
  service:
    image: registry.sciol.ac.cn/sciol/studio-service
    working_dir: /app
    build:
      context: ../service
      dockerfile: build/Dockerfile
    environment:
      - GOPROXY=https://goproxy.cn,direct
    env_file:
      - .env.dev
    volumes:
      - ../service:/app
    command: sh -c "go mod download && make dev"

  # mcps:
  #   image: registry.aissquare.com/web/service:dev
  #   pull_policy: if_not_present
  #   container_name: sciol-mcps
  #   restart: on-failure:5
  #   depends_on:
  #     service:
  #       condition: service_healthy
  #   env_file:
  #     - .env.dev
  #   volumes:
  #     - ../service:/app
  #   ports:
  #     - '48200:8000'
  #   command: sh -c "bash entrymcps.sh"

  # web:
  #   image: registry.aissquare.com/base/web:dev
  #   build:
  #     context: ../web
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env.dev
  #   volumes:
  #     - ../web:/app
  #   command: sh -c "if [ ! -d 'node_modules' ]; then yarn install; fi && yarn dev"
