services:
  service:
    image: registry.sciol.ac.cn/sciol/studio-service
    working_dir: /app
    build:
      context: ../service
      dockerfile: build/Dockerfile
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - GIN_MODE=debug
      - PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    env_file:
      - .env.dev
    volumes:
      - ../service:/app
      - go-mod-cache:/go/pkg/mod
      - go-bin-cache:/go/bin
    command: sh -c "go mod download && make dev"

  schedule:
    image: registry.sciol.ac.cn/sciol/studio-service
    working_dir: /app
    build:
      context: ../service
      dockerfile: build/Dockerfile
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - GIN_MODE=debug
      - PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    env_file:
      - .env.dev
    volumes:
      - ../service:/app
      - go-mod-cache:/go/pkg/mod
      - go-bin-cache:/go/bin
    command: sh -c "go mod download && make dev-schedule"

  web:
    image: registry.sciol.ac.cn/sciol/studio-web
    build:
      context: ../web
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ../web:/app
      - web-modules-cache:/app/node_modules
      - web-yarn-cache:/app/.yarn
    user: '0:0' # Run as root to avoid permission issues with corepack
    command: sh -c "corepack enable && yarn install && yarn dev"

volumes:
  web-modules-cache:
  web-yarn-cache:
  go-mod-cache:
  go-bin-cache:
