services:
  service:
    image: registry.sciol.ac.cn/sciol/studio-service
    working_dir: /app
    build:
      context: ../service
      dockerfile: build/Dockerfile
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - GIN_MODE=debug
    env_file:
      - .env.dev
    volumes:
      - ../service:/app
      - go-mod-cache:/go/pkg/mod
    command: sh -c "go mod download && make dev"

  web:
    image: registry.sciol.ac.cn/sciol/studio-web
    build:
      context: ../web
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ../web:/app
      - /app/node_modules
      - /app/.yarn
    user: '0:0' # Run as root to avoid permission issues with corepack
    command: sh -c "corepack enable && yarn install && yarn dev"

volumes:
  go-mod-cache:
