services:
  service:
    image: registry.aissquare.com/base/service:dev
    build:
      context: ../service
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ../service:/app

  web:
    image: registry.aissquare.com/base/web:dev
    build:
      context: ../web
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ../web:/app
    command: sh -c "if [ ! -d 'node_modules' ]; then yarn install; fi && yarn dev"
