// Code generated by "stringer -type ErrCode -linecomment -output code_string.go"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[UnDefineErr-1]
	_ = x[NoPermission-2]
	_ = x[ParamErr-1000]
	_ = x[NotPointerErr-1001]
	_ = x[NotSlicePointerErr-1002]
	_ = x[LoginConfigErr-5000]
	_ = x[LoginSetStateErr-5001]
	_ = x[RefreshTokenErr-5002]
	_ = x[LoginStateErr-5003]
	_ = x[ExchangeTokenErr-5004]
	_ = x[CallbackParamErr-5005]
	_ = x[LoginGetUserInfoErr-5006]
	_ = x[LoginCallbackErr-5007]
	_ = x[UnLogin-5008]
	_ = x[LoginFormatErr-5009]
	_ = x[InvalidToken-5010]
	_ = x[RefreshTokenParamErr-5011]
	_ = x[ParseLoginRedirectURLErr-5012]
	_ = x[CreateDataErr-10000]
	_ = x[UpdateDataErr-10001]
	_ = x[RecordNotFound-10002]
	_ = x[QueryRecordErr-10003]
	_ = x[DeleteDataErr-10004]
	_ = x[NotBaseDBTypeErr-10005]
	_ = x[ModelNotImplementTablerErr-10006]
	_ = x[RedisLuaScriptErr-10007]
	_ = x[RedisLuaRetErr-10008]
	_ = x[RedisAddSetErr-10009]
	_ = x[RedisRemoveSetErr-10010]
	_ = x[RegActionNameEmptyErr-20000]
	_ = x[ResourceIsEmptyErr-20001]
	_ = x[ResourceNotExistErr-20002]
	_ = x[WorkflowTemplateNotFoundErr-20003]
	_ = x[UserIDIsEmptyErr-20004]
	_ = x[LabIDIsEmptyErr-20005]
	_ = x[LabNotFound-20006]
	_ = x[LabInviteNotFoundErr-20007]
	_ = x[InviteExpiredErr-20008]
	_ = x[InvalidateThirdID-20009]
	_ = x[ResNotExistErr-22000]
	_ = x[EdgeNodeNotExistErr-22001]
	_ = x[EdgeHandleNotExistErr-22002]
	_ = x[UnknownWSActionErr-22003]
	_ = x[UnmarshalWSDataErr-22004]
	_ = x[CanNotGetLabIDErr-22005]
	_ = x[UpdateNodeErr-22006]
	_ = x[ParentNodeNotFoundErr-22007]
	_ = x[TemplateNodeNotFoundErr-22008]
	_ = x[InvalidDagErr-22009]
	_ = x[MaxTplNodeDeepErr-22010]
	_ = x[CanNotFoundMaterialNodeErr-22011]
	_ = x[NotifyActionAlreadyRegistryErr-24000]
	_ = x[NotifySubscribeChannelErr-24001]
	_ = x[NotifySendMsgErr-24002]
	_ = x[CasDoorCreateLabUserErr-26000]
	_ = x[CasDoorQueryLabUserErr-26001]
	_ = x[CanNotGetWorkflowUUIDErr-28000]
	_ = x[WorkflowNotExistErr-28001]
	_ = x[UpsertWorkflowEdgeErr-28002]
	_ = x[PermissionDenied-28003]
	_ = x[SaveWorkflowNodeErr-28004]
	_ = x[SaveWorkflowEdgeErr-28005]
	_ = x[WorkflowNodeNotFoundErr-28006]
	_ = x[CanNotGetworkflowErr-28007]
	_ = x[FormatCSVTaskErr-28008]
	_ = x[WorkflowTaskAlreadyExistErr-30000]
	_ = x[CanNotFoundEdgeSession-30001]
	_ = x[WorkflowHasCircularErr-30002]
	_ = x[EdgeConnectClosedErr-30003]
	_ = x[NodeDataMarshalErr-30004]
	_ = x[JobRetryTimeout-30005]
	_ = x[JobRunFailErr-30006]
	_ = x[WorkflowTaskNotFoundErr-30007]
	_ = x[WorkflowTaskStatusErr-30008]
	_ = x[WorkflowTaskFinished-30009]
}

const (
	_ErrCode_name_0 = "successundefinedno permission"
	_ErrCode_name_1 = "parse parameter errornot pointer errmust be a pointer to a slice"
	_ErrCode_name_2 = "login configuration errorset login state errorrefresh token failedstate verification failedexchange token failedcallback parameter errorget user info failedlogin process user info failednot logged inlogin verification format errorinvalid tokenrefresh token parameter errorredirect login url error"
	_ErrCode_name_3 = "database create data errordatabase update data errordatabase record not founddatabase query errordatabase delete errornot base db type errormodel not implement schema.Tablerredis lua script errorredis lua return type errorredis add user set errorredis remove user set error"
	_ErrCode_name_4 = "reg action name emptyresource is emptyresource not existcan not found workflow template erroruser id is emptylab id is empty errorlaboratory not found errorcan not found laboratory invite link errorinvite expired errorinvalidate third id error"
	_ErrCode_name_5 = "resource not existedge node not existnode handle not existunknown material websocket actionunmarshal material websocket data errorcannot get lab id errorupdate material node errorparent node not found errortemplate node not found errorinvalid dag errormax template node deep errorcan not found material node error"
	_ErrCode_name_6 = "notify action already registrynotify subscribe channel failnotify send message error"
	_ErrCode_name_7 = "create lab user errorquery lab user error"
	_ErrCode_name_8 = "can not get workflow uuidworkflow not existupsert workflow edge errorpermission deniedbatch save nodes errorbatch save workflow edge errorworkflow node not found errorworkflow not found errorformat csv data error"
	_ErrCode_name_9 = "workflow task already exist errorcan not found edge sessionworkflow has circular errorconnect closed when node running errormarshal node data errorjob retry timeout errorjob run fail errorcan not found workflow task errorworkflow task status errorworkflow task finished"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 7, 16, 29}
	_ErrCode_index_1 = [...]uint8{0, 21, 36, 64}
	_ErrCode_index_2 = [...]uint16{0, 25, 46, 66, 91, 112, 136, 156, 186, 199, 230, 243, 272, 296}
	_ErrCode_index_3 = [...]uint16{0, 26, 52, 77, 97, 118, 140, 173, 195, 222, 246, 273}
	_ErrCode_index_4 = [...]uint8{0, 21, 38, 56, 93, 109, 130, 156, 198, 218, 243}
	_ErrCode_index_5 = [...]uint16{0, 18, 37, 58, 91, 130, 153, 179, 206, 235, 252, 280, 313}
	_ErrCode_index_6 = [...]uint8{0, 30, 59, 84}
	_ErrCode_index_7 = [...]uint8{0, 21, 41}
	_ErrCode_index_8 = [...]uint8{0, 25, 43, 69, 86, 108, 138, 167, 191, 212}
	_ErrCode_index_9 = [...]uint16{0, 33, 59, 86, 124, 147, 170, 188, 221, 247, 269}
)

func (i ErrCode) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case 1000 <= i && i <= 1002:
		i -= 1000
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case 5000 <= i && i <= 5012:
		i -= 5000
		return _ErrCode_name_2[_ErrCode_index_2[i]:_ErrCode_index_2[i+1]]
	case 10000 <= i && i <= 10010:
		i -= 10000
		return _ErrCode_name_3[_ErrCode_index_3[i]:_ErrCode_index_3[i+1]]
	case 20000 <= i && i <= 20009:
		i -= 20000
		return _ErrCode_name_4[_ErrCode_index_4[i]:_ErrCode_index_4[i+1]]
	case 22000 <= i && i <= 22011:
		i -= 22000
		return _ErrCode_name_5[_ErrCode_index_5[i]:_ErrCode_index_5[i+1]]
	case 24000 <= i && i <= 24002:
		i -= 24000
		return _ErrCode_name_6[_ErrCode_index_6[i]:_ErrCode_index_6[i+1]]
	case 26000 <= i && i <= 26001:
		i -= 26000
		return _ErrCode_name_7[_ErrCode_index_7[i]:_ErrCode_index_7[i+1]]
	case 28000 <= i && i <= 28008:
		i -= 28000
		return _ErrCode_name_8[_ErrCode_index_8[i]:_ErrCode_index_8[i+1]]
	case 30000 <= i && i <= 30009:
		i -= 30000
		return _ErrCode_name_9[_ErrCode_index_9[i]:_ErrCode_index_9[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
