basePath: /
definitions:
  code.ErrCode:
    enum:
    - 0
    - 0
    - 1000
    - 1001
    - 1002
    - 1003
    - 1004
    - 1005
    - 1006
    - 1007
    - 1008
    - 1009
    - 1010
    - 1011
    type: integer
    x-enum-comments:
      CallbackParamErr: 回调参数错误
      ExchangeTokenErr: 交换 token 失败
      InvalidToken: 无效 token
      LoginCallbackErr: 登录处理用户信息失败
      LoginConfigErr: 登录配置错误
      LoginFormatErr: 登录验证格式错误
      LoginGetUserInfoErr: 获取用户信息失败
      LoginSetStateErr: 设置登录状态错误
      LoginStateErr: state 验证失败
      RefreshTokenErr: 刷新 token 失败
      RefreshTokenParamErr: 刷新 token 参数错误
      Success: 成功
      UnDefineErr: 未定义
      UnLogin: 未登录状态
    x-enum-varnames:
    - Success
    - UnDefineErr
    - LoginConfigErr
    - LoginSetStateErr
    - RefreshTokenErr
    - LoginStateErr
    - ExchangeTokenErr
    - CallbackParamErr
    - LoginGetUserInfoErr
    - LoginCallbackErr
    - UnLogin
    - LoginFormatErr
    - InvalidToken
    - RefreshTokenParamErr
  common.Error:
    properties:
      msg:
        type: string
    type: object
  common.Resp:
    properties:
      code:
        $ref: '#/definitions/code.ErrCode'
      data: {}
      error:
        $ref: '#/definitions/common.Error'
    type: object
  types.RefreshTokenReq:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  types.RefreshTokenResp:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      token_type:
        type: string
    type: object
host: localhost:48197
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Studio 实验室管理系统 API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Studio API
  version: "1.0"
paths:
  /api/auth/callback/casdoor:
    get:
      consumes:
      - application/json
      description: 处理OAuth2授权回调
      parameters:
      - description: 授权码
        in: query
        name: code
        required: true
        type: string
      - description: 防CSRF攻击的状态码
        in: query
        name: state
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/common.Resp'
      summary: OAuth2回调
      tags:
      - 登录模块
  /api/auth/login:
    get:
      consumes:
      - application/json
      description: 检查服务运行状态
      produces:
      - application/json
      responses:
        "302":
          description: 重定向到OAuth2授权页面
          headers:
            Location:
              description: 重定向的授权URL地址
              type: string
          schema:
            type: string
      summary: 登录
      tags:
      - 登录模块
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      description: 刷新OAuth2令牌
      parameters:
      - description: 刷新令牌请求
        in: body
        name: refresh_token
        required: true
        schema:
          $ref: '#/definitions/types.RefreshTokenReq'
      produces:
      - application/json
      responses:
        "200":
          description: 刷新 token 失败 code = 1002
          schema:
            allOf:
            - $ref: '#/definitions/common.Resp'
            - properties:
                code:
                  $ref: '#/definitions/code.ErrCode'
              type: object
      summary: 刷新令牌
      tags:
      - 登录模块
  /api/health:
    get:
      consumes:
      - application/json
      description: 检查服务运行状态
      produces:
      - application/json
      responses:
        "200":
          description: 返回成功状态
          schema:
            additionalProperties: true
            type: object
      summary: 健康检查
      tags:
      - health
swagger: "2.0"
