name: Merge Tag to Main

on:
  push:
    tags:
      - 'v*'

jobs:
  merge-tag-to-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.DEV_PAT }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Validate Event Type
        id: check_event
        run: |
          if [[ "${{ github.ref_type }}" != "tag" ]]; then
            echo "::error::This workflow only responds to tag events!"
            exit 1
          fi

      - name: Validate Tag Format
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ ! $TAG_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Tag $TAG_NAME 不符合 SemVer 规范!"
            exit 1
          fi

      - name: Get Tag Commit
        id: get_tag
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          echo "tag_commit=$TAG_COMMIT" >> $GITHUB_OUTPUT

      - name: Merge Tag into Main
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          git merge --no-ff ${{ steps.get_tag.outputs.tag_commit }} -m "Merge tag ${TAG_NAME} into main"
          if [ $? -ne 0 ]; then
            echo "::error::Merge conflict detected! Resolve conflicts manually."
            exit 1
          fi

      - name: Push to Main
        run: git push origin main

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.feishu.cn
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: '已合并 ${{ github.ref_name }} 到 main'
          body: '查看提交：https://github.com/${{ github.repository }}/commit/${{ steps.get_tag.outputs.tag_commit }}'
          from: PROTIUM
          to: quehaohui@dp.tech